/**
 * EN + DE copy for the dashboard and the case-complete card. Object · state ·
 * owner · next step — never capability claims.
 */

import { useProcurement } from "@/mro/data/store";

const en = {
  title: "Dashboard",
  search: "Search cases, invoices",
  newRequest: "New request",
  read1: (n: number, w: number, wv: string, h: number, hv: string) =>
    `${n} requests in flight · ${w} waiting on a decision (${wv}) · ${h} invoice${h === 1 ? "" : "s"} held (${hv}).`,
  priority: (role: string, ref: string, task: string) => `First up: ${role} on ${ref} — ${task}.`,
  nothingWaiting: (n: number) => `Nothing is waiting on a person. ${n} cases closed so far.`,
  statNeedYou: "need a decision",
  statHeld: "invoice variance",
  statTouchless: "fully touchless",
  kpiInFlight: "In flight",
  kpiInFlightSub: (sites: number, v: string) => `${v} across ${sites} site${sites === 1 ? "" : "s"}`,
  kpiWaiting: "Waiting on people",
  kpiWaitingSub: (v: string) => `${v} awaiting a named approver`,
  kpiClosed: "Closed",
  kpiClosedSub: (t: number, e: number) => `${t} of ${e} orders placed with no human touch`,
  kpiInvoice: "Invoice holds",
  kpiInvoiceSub: (a: number, b: number) => `${a} of ${b} invoices held on variance`,
  requisitions: "Requisitions",
  reqRight: (n: number) => `${n} open`,
  exceptions: "Decisions and holds",
  excRight: (n: number) => `${n} open`,
  decision: "Decision",
  hold: "Hold",
  nothingStopped: "Nothing is stopped.",
  invoices: "Invoice matching",
  invRight: (v: string) => `${v} held`,
  colInvoice: "Invoice",
  colAmount: "Amount",
  colStatus: "Status",
  invRecords: (po: string, gr: string) => `${po} · ${gr}`,
  matched: "Matched",
  credited: "Credited",
  heldAmt: (v: string) => `Held · ${v}`,
  noInvoices: "No invoices yet.",
  heldByReason: "Held value by reason",
  noHeld: "No value is held.",
  barInvoice: "Invoice",
  barChase: "Supplier ack",
  barErp: "ERP",
  byStatus: "Requests by status",
  phase: { running: "Agents running", waiting: "Waiting on a person", ordered: "PO dispatched", closed: "Closed" },
  showMore: (n: number) => `Show ${n} more`,
  notifications: "Notifications",
  needYou: (n: number) => `${n} need you`,
  fromSuppliers: "From suppliers",
  supplierAsked: "Supplier question waiting for an answer",
  open: "Open",
  allClear: "Nothing needs you right now.",
  story: "Story",
  catalogue: "Catalogue",
  /* Case-complete card */
  complete: "Case complete",
  endedEarly: "Case closed early",
  closedTouchless: "closed, fully touchless",
  closedAfter: (n: number) => `closed after ${n} human decision${n === 1 ? "" : "s"}`,
  closedEnded: "closed by decision",
  manualTouch: "manual touchpoints",
  poValue: "PO value",
  cycle: "demo-clock cycle",
  processing: "processing",
  touchless: "Touchless",
  humanReviewed: "Human-reviewed",
  agentsRan: "agents ran",
  requestValue: "request value",
  costAvoided: "cost avoided · Finance to sign",
  expectedSaving: "expected saving · awaits invoice",
  produced: "Records this case produced",
  pr: (id: string) => `Purchase request ${id}`,
  approval: (role: string) => `Approval · ${role}`,
  po: (id: string) => `Purchase order ${id}`,
  supplierAck: "Supplier confirmation",
  valueRecord: (id: string) => `Value record ${id}`,
  docKind: { receipt: "Goods receipt", invoice: "Invoice", credit: "Credit note", rfq: "RFQ", quote: "Quote", bafo: "BAFO", award: "Award", contract: "Contract", reservation: "Reservation", assignment: "Assignment", equivalence: "Equivalence", onboarding: "Onboarding", "panel-match": "Panel match", "protected-terms": "Protected terms" } as Record<string, string>,
  stay: "Stay on this case",
  back: "Back to dashboard",
  summary: "Case summary",
  toConfirmation: (h: number) => `Advance clock to supplier confirmation · +${h}h`,
};

type Copy = typeof en;

const de: Copy = {
  title: "Übersicht",
  search: "Fälle, Rechnungen suchen",
  newRequest: "Neue Anforderung",
  read1: (n, w, wv, h, hv) => `${n} Anforderungen in Bearbeitung · ${w} warten auf Entscheidung (${wv}) · ${h} Rechnung${h === 1 ? "" : "en"} gehalten (${hv}).`,
  priority: (role, ref, task) => `Als Nächstes: ${role} bei ${ref} — ${task}.`,
  nothingWaiting: (n) => `Nichts wartet auf eine Person. ${n} Fälle bisher abgeschlossen.`,
  statNeedYou: "brauchen Entscheidung",
  statHeld: "Rechnungsabweichung",
  statTouchless: "vollständig ohne Eingriff",
  kpiInFlight: "In Bearbeitung",
  kpiInFlightSub: (sites, v) => `${v} an ${sites} Standort${sites === 1 ? "" : "en"}`,
  kpiWaiting: "Warten auf Personen",
  kpiWaitingSub: (v) => `${v} bei benannten Genehmigern`,
  kpiClosed: "Abgeschlossen",
  kpiClosedSub: (t, e) => `${t} von ${e} Bestellungen ohne Eingriff`,
  kpiInvoice: "Rechnungssperren",
  kpiInvoiceSub: (a, b) => `${a} von ${b} Rechnungen wegen Abweichung gehalten`,
  requisitions: "Bestellanforderungen",
  reqRight: (n) => `${n} offen`,
  exceptions: "Entscheidungen und Sperren",
  excRight: (n) => `${n} offen`,
  decision: "Entscheidung",
  hold: "Sperre",
  nothingStopped: "Nichts ist gestoppt.",
  invoices: "Rechnungsprüfung",
  invRight: (v) => `${v} gehalten`,
  colInvoice: "Rechnung",
  colAmount: "Betrag",
  colStatus: "Status",
  invRecords: (po, gr) => `${po} · ${gr}`,
  matched: "Abgeglichen",
  credited: "Gutgeschrieben",
  heldAmt: (v) => `Gehalten · ${v}`,
  noInvoices: "Noch keine Rechnungen.",
  heldByReason: "Gehaltener Wert nach Grund",
  noHeld: "Kein Wert gehalten.",
  barInvoice: "Rechnung",
  barChase: "Lieferantenbest.",
  barErp: "ERP",
  byStatus: "Anforderungen nach Status",
  phase: { running: "Agenten laufen", waiting: "Wartet auf Person", ordered: "Bestellung versandt", closed: "Abgeschlossen" },
  showMore: (n) => `${n} weitere anzeigen`,
  notifications: "Benachrichtigungen",
  needYou: (n) => `${n} brauchen Sie`,
  fromSuppliers: "Von Lieferanten",
  supplierAsked: "Lieferantenfrage wartet auf Antwort",
  open: "Öffnen",
  allClear: "Gerade braucht Sie nichts.",
  story: "Story",
  catalogue: "Katalog",
  complete: "Fall abgeschlossen",
  endedEarly: "Fall vorzeitig geschlossen",
  closedTouchless: "abgeschlossen, ohne Eingriff",
  closedAfter: (n) => `abgeschlossen nach ${n} Entscheidung${n === 1 ? "" : "en"}`,
  closedEnded: "durch Entscheidung geschlossen",
  manualTouch: "manuelle Eingriffe",
  poValue: "Bestellwert",
  cycle: "Durchlaufzeit (Demo-Uhr)",
  processing: "Bearbeitung",
  touchless: "Ohne Eingriff",
  humanReviewed: "Menschlich geprüft",
  agentsRan: "Agenten liefen",
  requestValue: "Anforderungswert",
  costAvoided: "vermiedene Kosten · Finance zeichnet",
  expectedSaving: "erwartete Einsparung · wartet auf Rechnung",
  produced: "Belege dieses Falls",
  pr: (id) => `Bestellanforderung ${id}`,
  approval: (role) => `Freigabe · ${role}`,
  po: (id) => `Bestellung ${id}`,
  supplierAck: "Lieferantenbestätigung",
  valueRecord: (id) => `Werteintrag ${id}`,
  docKind: { receipt: "Wareneingang", invoice: "Rechnung", credit: "Gutschrift", rfq: "Anfrage", quote: "Angebot", bafo: "BAFO", award: "Vergabe", contract: "Vertrag", reservation: "Reservierung", assignment: "Zuweisung", equivalence: "Gleichwertigkeit", onboarding: "Onboarding", "panel-match": "Panel-Abgleich", "protected-terms": "Geschützte Bedingungen" },
  stay: "Im Fall bleiben",
  back: "Zur Übersicht",
  summary: "Fallübersicht",
  toConfirmation: (h) => `Uhr bis Lieferantenbestätigung · +${h} h`,
};

export type DashCopy = Copy;

export function useDashCopy(): Copy {
  const { lang } = useProcurement();
  return lang === "de" ? de : en;
}
