/**
 * EN + DE copy for the case-driven pages: My Desk, the catalogue case
 * workspace, presenter controls, workbenches, Value Assurance and Governance.
 * Written as object · state · owner · next step, never as capability claims.
 */

import { useT } from "@/mro/lib/i18n";

const en = {
  /* My Desk */
  deskTitle: "My desk",
  deskLead: "Requests, approvals and holds that need you, across the UK sites.",
  newRequest: "New request",
  newRequestHint: "Type a need or open one of today's arrivals",
  qRequests: "Requests in flight",
  qApprovals: "Approvals waiting",
  qExceptions: "Holds and exceptions",
  qEmptyRequests: "Nothing in flight. Start with New request.",
  qEmptyApprovals: "No approvals waiting for anyone.",
  qEmptyExceptions: "No open holds.",
  forRole: (r: string) => `For ${r}`,
  youCanDecide: "You can decide",
  open: "Open",
  touchMetrics: "Touch ledger",
  completed: "Completed",
  noBuyerTouch: "No buyer touch",
  fullyTouchless: "Fully touchless",
  story: "Story",
  catalogue: "Catalogue",

  /* Composer */
  composeTitle: "Write a request",
  composePlaceholder: "e.g. Need 10 packs of 3M 6055 A2 filters for Halewood stores by 12 Oct.",
  examples: "Examples",
  exTen: "10 packs · £480",
  exBig: "120 packs · £5,760",
  exVague: "Vague request",
  understood: "What intake understood",
  field: { material: "Item", quantity: "Quantity", site: "Site", neededBy: "Needed by" },
  missing: "Missing",
  assumed: "Assumed",
  submit: "Submit request",
  submitting: "Submitting",
  missingBlock: (f: string) => `Add ${f} before submitting. The original text is kept.`,
  catalogueMatch: (a: string, p: string) => `Catalogue ${a} · ${p}`,
  noCatalogue: "No live catalogue line",
  todayArrivals: "Today's arrivals from the use cases",

  /* Case workspace */
  backDesk: "My desk",
  steps: { intake: "Intake", classify: "Classify & policy", approval: "Approval", po: "Purchase order", followUp: "Follow-up" },
  stepState: { done: "Done", current: "In progress", waiting: "Waiting", todo: "Not started", failed: "Failed" },
  request: "Request",
  original: "As written",
  line: "Line",
  qty: "Quantity",
  unitPrice: "Unit price",
  total: "Total",
  agreement: "Agreement",
  supplier: "Supplier",
  revise: "Change quantity",
  reviseHint: "A change creates a new revision. Earlier approvals stop covering it.",
  update: "Update request",
  lockedByPo: "PO already dispatched for this revision",
  gate: "Gate",
  gateLead: "Scope, hard controls, authority, lane, confidence — in that order",
  laneLabel: "Lane",
  confidence: "Confidence",
  authority: "Authority",
  standing: (m: string) => `Standing mandate ${m}`,
  needsRole: (r: string) => `Needs ${r}`,
  controls: "Hard controls",
  approvalTask: "Approval task",
  due: "Due",
  amount: "Amount",
  decision: "Decision",
  approve: "Approve",
  reject: "Reject",
  rejectReason: "Quantity above the stores plan",
  reviewingAs: (r: string) => `You are reviewing as ${r}.`,
  onlyRole: (r: string) => `Only the ${r} can decide this.`,
  switchTo: (r: string) => `Review as ${r}`,
  decided: (o: string, by: string) => `${o} by ${by}`,
  approved: "Approved",
  rejected: "Rejected",
  po: "Purchase order",
  poNone: "No PO yet",
  poHeld: "PO held until approval covers this revision",
  dispatched: "Dispatched to ERP",
  ackDue: "Supplier confirmation due",
  acked: "Supplier confirmed",
  chaser: "Chaser opened",
  timeline: "Case timeline",
  duplicateOf: (id: string) => `Possible duplicate of ${id}. Both stay open.`,
  holdOpen: "Hold",
  clock: "Demo clock",

  /* Presenter */
  presenter: "Presenter controls",
  presenterLead: "Outside the normal flow. Nothing here skips a gate.",
  reviewAs: "Review as",
  pendingFor: (n: number) => `${n} waiting`,
  supplierSeat: "Supplier seat",
  advance: "Advance the clock",
  failures: "Failure injection",
  erpFail: "ERP rejects the next PO (3 attempts)",
  supplierSilent: "Supplier withholds confirmation",
  launch: "Launch a story",
  legacy: "Legacy scenarios",
  reset: "Reset demo",
  resetConfirm: "Clear every case, decision, sign-off and the clock?",
  resetYes: "Yes, reset",
  cancel: "Cancel",
  close: "Close",

  /* Workbenches */
  oppTitle: "Opportunities",
  oppLead: "Flow 0 pipeline items raised by agents. Live only after the Category Lead accepts.",
  srcTitle: "Sourcing",
  srcLead: "RFQs and quote evaluations from Flow 2.",
  supTitle: "Suppliers",
  supLead: "Panel fit, onboarding and risk screening from Flow 4.",
  conTitle: "Contracts",
  conLead: "Drafts and clause decisions from Flow 3. A PO stays blocked until the contract is stored.",
  notRun: "Not run yet",
  surfacedBy: (c: string) => `Raised by ${c}`,
  accept: "Accept",
  decline: "Decline",
  awaitingCategory: "Awaiting Category Lead",
  live: "Live",
  declined: "Declined",
  est: "Est. value",
  lever: "Lever",
  owner: "Owner",
  status: "Status",
  openCase: "Open case",
  issuedTo: "Issued to",
  window: "Window",
  quotes: "Quotes",
  best: "Best evaluated",
  award: "Award",
  panel: "Panel",
  onboarding: "Onboarding",
  risk: "Risk tier",
  conditions: "Conditions",
  clauses: "Clauses",
  stored: "Stored",
  blocked: "PO blocked",
  target: "Target",
  rfqCol: "RFQ",
  draftCol: "Draft",

  /* Value */
  valTitle: "Value assurance",
  valLead: "Expected value becomes validated only with invoice evidence and a Finance sign-off.",
  expected: "Expected",
  evidenced: "Evidenced",
  validated: "Validated",
  notClaimed: "Not claimed",
  category: "Category",
  baseline: "Baseline",
  value: "Value",
  measurement: "Measurement",
  recordEvidence: "Record invoice evidence",
  recordReceipt: "Record usage evidence",
  signOff: "Finance sign-off",
  signedBy: (b: string) => `Signed by ${b}`,
  awaitingRun: "Run not finished",
  cats: { "sourcing-saving": "Sourcing saving", "cost-avoidance": "Cost avoidance", "non-cash": "Non-cash protection" },
  states: {
    pending: "Run not finished",
    expected: "Expected",
    "awaiting-invoice": "Awaiting invoice",
    "awaiting-finance": "Awaiting Finance",
    validated: "Validated",
    "not-claimed": "Not claimed",
  },
  cashValidated: "Cash saving validated",
  avoidanceValidated: "Cost avoidance validated",
  pipelineExpected: "Expected, not yet validated",

  /* Governance */
  govTitle: "Governance",
  govLead: "Policy versions, rule changes and agent controls. Changes need the Value Council.",
  activePolicy: "Active policy",
  autoLimit: "Auto-approve limit",
  doa: "Spend authority",
  lanes: "Confidence lanes",
  ruleChanges: "Rule change proposals",
  from: "From",
  to: "To",
  tests: "Tests",
  effective: "Effective",
  rollback: "Rollback to",
  approveChange: "Approve change",
  rejectChange: "Reject",
  onlyCouncil: "Only the Value Council can approve a rule change.",
  testsFailed: "Tests failed — the active version stays in force.",
  agents: "Agents",
  pause: "Pause",
  resume: "Resume",
  paused: "Paused",
  activeAgent: "Active",
  pauseHint: "Paused work returns to the human queue. Dispatched actions are not replayed.",
  versions: "Versions",
  casesKeepPolicy: "Existing cases keep the policy they were opened under.",

  /* Control tower */
  ctTitle: "Control tower",
  ctLead: "Spend in flight, value and workload across the UK sites, in GBP.",
  site: "Site",
  inFlight: "In flight",
  cases: "Cases",
  openTasks: "Open human tasks",
  drill: "Open",
};

export type DeskCopy = typeof en;

const de: DeskCopy = {
  deskTitle: "Mein Desk",
  deskLead: "Anforderungen, Freigaben und Sperren, die Sie betreffen, über alle UK-Standorte.",
  newRequest: "Neue Anforderung",
  newRequestHint: "Bedarf eingeben oder einen heutigen Eingang öffnen",
  qRequests: "Laufende Anforderungen",
  qApprovals: "Offene Freigaben",
  qExceptions: "Sperren und Ausnahmen",
  qEmptyRequests: "Nichts in Bearbeitung. Mit Neue Anforderung beginnen.",
  qEmptyApprovals: "Keine offenen Freigaben.",
  qEmptyExceptions: "Keine offenen Sperren.",
  forRole: (r) => `Für ${r}`,
  youCanDecide: "Sie können entscheiden",
  open: "Öffnen",
  touchMetrics: "Eingriffsbuch",
  completed: "Abgeschlossen",
  noBuyerTouch: "Ohne Einkäufer",
  fullyTouchless: "Vollständig ohne Eingriff",
  story: "Story",
  catalogue: "Katalog",

  composeTitle: "Anforderung schreiben",
  composePlaceholder: "z. B. Need 10 packs of 3M 6055 A2 filters for Halewood stores by 12 Oct.",
  examples: "Beispiele",
  exTen: "10 Packungen · £480",
  exBig: "120 Packungen · £5.760",
  exVague: "Unklare Anforderung",
  understood: "Was die Erfassung verstanden hat",
  field: { material: "Artikel", quantity: "Menge", site: "Standort", neededBy: "Benötigt bis" },
  missing: "Fehlt",
  assumed: "Angenommen",
  submit: "Anforderung einreichen",
  submitting: "Wird eingereicht",
  missingBlock: (f) => `Vor dem Einreichen ergänzen: ${f}. Der Originaltext bleibt erhalten.`,
  catalogueMatch: (a, p) => `Katalog ${a} · ${p}`,
  noCatalogue: "Keine gültige Katalogzeile",
  todayArrivals: "Heutige Eingänge aus den Use Cases",

  backDesk: "Mein Desk",
  steps: { intake: "Erfassung", classify: "Klassifizierung & Regeln", approval: "Freigabe", po: "Bestellung", followUp: "Nachverfolgung" },
  stepState: { done: "Erledigt", current: "In Bearbeitung", waiting: "Wartet", todo: "Nicht begonnen", failed: "Fehlgeschlagen" },
  request: "Anforderung",
  original: "Wie geschrieben",
  line: "Position",
  qty: "Menge",
  unitPrice: "Einzelpreis",
  total: "Summe",
  agreement: "Vereinbarung",
  supplier: "Lieferant",
  revise: "Menge ändern",
  reviseHint: "Eine Änderung erzeugt eine neue Revision. Frühere Freigaben gelten dafür nicht mehr.",
  update: "Anforderung aktualisieren",
  lockedByPo: "Bestellung für diese Revision bereits übermittelt",
  gate: "Prüfung",
  gateLead: "Umfang, harte Kontrollen, Befugnis, Pfad, Konfidenz – in dieser Reihenfolge",
  laneLabel: "Pfad",
  confidence: "Konfidenz",
  authority: "Befugnis",
  standing: (m) => `Dauermandat ${m}`,
  needsRole: (r) => `Benötigt ${r}`,
  controls: "Harte Kontrollen",
  approvalTask: "Freigabeaufgabe",
  due: "Fällig",
  amount: "Betrag",
  decision: "Entscheidung",
  approve: "Freigeben",
  reject: "Ablehnen",
  rejectReason: "Menge über dem Lagerplan",
  reviewingAs: (r) => `Sie prüfen als ${r}.`,
  onlyRole: (r) => `Nur ${r} kann das entscheiden.`,
  switchTo: (r) => `Als ${r} prüfen`,
  decided: (o, by) => `${o} von ${by}`,
  approved: "Freigegeben",
  rejected: "Abgelehnt",
  po: "Bestellung",
  poNone: "Noch keine Bestellung",
  poHeld: "Bestellung gesperrt, bis die Freigabe diese Revision abdeckt",
  dispatched: "An ERP übermittelt",
  ackDue: "Lieferantenbestätigung fällig",
  acked: "Lieferant hat bestätigt",
  chaser: "Erinnerung eröffnet",
  timeline: "Vorgangsverlauf",
  duplicateOf: (id) => `Mögliches Duplikat von ${id}. Beide bleiben offen.`,
  holdOpen: "Sperre",
  clock: "Demo-Uhr",

  presenter: "Präsentationssteuerung",
  presenterLead: "Außerhalb des normalen Ablaufs. Nichts hier überspringt eine Prüfung.",
  reviewAs: "Prüfen als",
  pendingFor: (n) => `${n} wartend`,
  supplierSeat: "Lieferantenplatz",
  advance: "Uhr vorstellen",
  failures: "Fehler einspielen",
  erpFail: "ERP lehnt nächste Bestellung ab (3 Versuche)",
  supplierSilent: "Lieferant hält Bestätigung zurück",
  launch: "Story starten",
  legacy: "Alte Szenarien",
  reset: "Demo zurücksetzen",
  resetConfirm: "Alle Vorgänge, Entscheidungen, Freigaben und die Uhr löschen?",
  resetYes: "Ja, zurücksetzen",
  cancel: "Abbrechen",
  close: "Schließen",

  oppTitle: "Chancen",
  oppLead: "Flow-0-Pipeline aus Agentensignalen. Aktiv erst nach Annahme durch die Warengruppenleitung.",
  srcTitle: "Sourcing",
  srcLead: "Anfragen und Angebotsbewertungen aus Flow 2.",
  supTitle: "Lieferanten",
  supLead: "Panel-Eignung, Onboarding und Risikoprüfung aus Flow 4.",
  conTitle: "Verträge",
  conLead: "Entwürfe und Klauselentscheidungen aus Flow 3. Bestellung gesperrt, bis der Vertrag abgelegt ist.",
  notRun: "Noch nicht gelaufen",
  surfacedBy: (c) => `Ausgelöst durch ${c}`,
  accept: "Annehmen",
  decline: "Ablehnen",
  awaitingCategory: "Wartet auf Warengruppenleitung",
  live: "Aktiv",
  declined: "Abgelehnt",
  est: "Gesch. Wert",
  lever: "Hebel",
  owner: "Verantwortlich",
  status: "Status",
  openCase: "Vorgang öffnen",
  issuedTo: "Angefragt bei",
  window: "Zeitfenster",
  quotes: "Angebote",
  best: "Bestbewertet",
  award: "Vergabe",
  panel: "Panel",
  onboarding: "Onboarding",
  risk: "Risikostufe",
  conditions: "Auflagen",
  clauses: "Klauseln",
  stored: "Abgelegt",
  blocked: "Bestellung gesperrt",
  target: "Ziel",
  rfqCol: "Anfrage",
  draftCol: "Entwurf",

  valTitle: "Wertsicherung",
  valLead: "Erwarteter Wert gilt erst mit Rechnungsnachweis und Freigabe durch Finance als bestätigt.",
  expected: "Erwartet",
  evidenced: "Nachgewiesen",
  validated: "Bestätigt",
  notClaimed: "Nicht beansprucht",
  category: "Kategorie",
  baseline: "Basis",
  value: "Wert",
  measurement: "Messung",
  recordEvidence: "Rechnungsnachweis erfassen",
  recordReceipt: "Nutzungsnachweis erfassen",
  signOff: "Finance-Freigabe",
  signedBy: (b) => `Freigegeben von ${b}`,
  awaitingRun: "Lauf nicht beendet",
  cats: { "sourcing-saving": "Beschaffungseinsparung", "cost-avoidance": "Kostenvermeidung", "non-cash": "Nicht-monetärer Schutz" },
  states: {
    pending: "Lauf nicht beendet",
    expected: "Erwartet",
    "awaiting-invoice": "Wartet auf Rechnung",
    "awaiting-finance": "Wartet auf Finance",
    validated: "Bestätigt",
    "not-claimed": "Nicht beansprucht",
  },
  cashValidated: "Einsparung bestätigt",
  avoidanceValidated: "Kostenvermeidung bestätigt",
  pipelineExpected: "Erwartet, noch nicht bestätigt",

  govTitle: "Governance",
  govLead: "Richtlinienversionen, Regeländerungen und Agentensteuerung. Änderungen brauchen das Wertgremium.",
  activePolicy: "Aktive Richtlinie",
  autoLimit: "Automatische Freigabegrenze",
  doa: "Ausgabebefugnis",
  lanes: "Konfidenzpfade",
  ruleChanges: "Regeländerungsvorschläge",
  from: "Von",
  to: "Auf",
  tests: "Tests",
  effective: "Gültig ab",
  rollback: "Rückfall auf",
  approveChange: "Änderung freigeben",
  rejectChange: "Ablehnen",
  onlyCouncil: "Nur das Wertgremium kann eine Regeländerung freigeben.",
  testsFailed: "Tests fehlgeschlagen – die aktive Version bleibt in Kraft.",
  agents: "Agenten",
  pause: "Pausieren",
  resume: "Fortsetzen",
  paused: "Pausiert",
  activeAgent: "Aktiv",
  pauseHint: "Pausierte Arbeit geht an die menschliche Warteschlange. Übermittelte Aktionen werden nicht wiederholt.",
  versions: "Versionen",
  casesKeepPolicy: "Bestehende Vorgänge behalten ihre Eröffnungsrichtlinie.",

  ctTitle: "Leitstand",
  ctLead: "Laufende Ausgaben, Wert und Arbeitslast über die UK-Standorte, in GBP.",
  site: "Standort",
  inFlight: "In Bearbeitung",
  cases: "Vorgänge",
  openTasks: "Offene menschliche Aufgaben",
  drill: "Öffnen",
};

export function useDeskCopy() {
  const { lang, t } = useT();
  const l = lang === "de" ? ("de" as const) : ("en" as const);
  /** Role label with a leading capital, e.g. "Budget holder". */
  const role = (r: string) => {
    const s = t(`role.${r}`);
    return s.charAt(0).toUpperCase() + s.slice(1);
  };
  return { d: l === "de" ? de : en, lang: l, t, role };
}
