import { useStoryCopy } from "@/mro/components/story/copy";

const en = {
  newRequest: "New request",
  requester: "Requester",
  need: "Need",
  item: "Item",
  startingCost: "Starting cost",
  needBy: "Needed by",
  received: "Received",
  openForm: "Open the form",
  start: (agent: string) => `Start ${agent}`,
  notNow: "Not now",
  awaiting: "Request received",
  working: "Working",
  fetched: "fetched",
  fetching: "Fetching sources",
  analyseConfidence: "AI · Score confidence",
  analyseGuardrails: "AI · Run guardrail checks",
  scoringTitle: "Scoring confidence",
  guardTitle: "Running guardrail checks",
  scoringDoc: "confidence score",
  guardDoc: "guardrail verdicts",
  analyseChecks: "AI · Score confidence & run guardrails",
  checksTitle: "Scoring confidence & running guardrails",
  checksDoc: "confidence score & guardrail verdicts",
  confidenceResult: (s: string, band: string) => `Confidence ${s} · ${band}`,
  guardResult: (pass: number, total: number) => `${pass} of ${total} guardrails passed`,
  deciding: "Deciding the routing lane…",
  handover: "Handover",
  closing: "Closing the case",
  done: "Done",
  wakingUp: "Taking over",
  passing: "Passing on",
  sourceFiles: "Source files",
  sourceLead: "The originals each agent read or wrote. Open any of them.",
  noneYet: "Files appear here as the agents fetch them.",
  open: "Open",
  bands: { touchless: "touchless band ≥ 0.90", review: "TCS review band 0.70–0.89", client: "Client decides < 0.70" },
};

type Copy = typeof en;

const de: Copy = {
  newRequest: "Neue Anforderung",
  requester: "Anforderer",
  need: "Bedarf",
  item: "Position",
  startingCost: "Ausgangskosten",
  needBy: "Benötigt bis",
  received: "Eingegangen",
  openForm: "Formular öffnen",
  start: (agent) => `${agent} starten`,
  notNow: "Später",
  awaiting: "Anforderung eingegangen",
  working: "Arbeitet",
  fetched: "geladen",
  fetching: "Lade Quellen",
  analyseConfidence: "KI · Konfidenz bewerten",
  analyseGuardrails: "KI · Leitplanken prüfen",
  scoringTitle: "Konfidenz wird bewertet",
  guardTitle: "Leitplanken werden geprüft",
  scoringDoc: "Konfidenzwert",
  guardDoc: "Leitplanken-Ergebnis",
  analyseChecks: "KI · Konfidenz bewerten & Leitplanken prüfen",
  checksTitle: "Konfidenz und Leitplanken werden geprüft",
  checksDoc: "Konfidenzwert & Leitplanken-Ergebnis",
  confidenceResult: (s, band) => `Konfidenz ${s} · ${band}`,
  guardResult: (pass, total) => `${pass} von ${total} Leitplanken bestanden`,
  deciding: "Bearbeitungsweg wird entschieden…",
  handover: "Übergabe",
  closing: "Fall wird abgeschlossen",
  done: "Fertig",
  wakingUp: "Übernimmt",
  passing: "Übergibt",
  sourceFiles: "Quelldateien",
  sourceLead: "Die Originale, die jeder Agent gelesen oder erstellt hat.",
  noneYet: "Dateien erscheinen hier, sobald die Agenten sie laden.",
  open: "Öffnen",
  bands: { touchless: "Touchless-Band ≥ 0,90", review: "TCS-Prüfband 0,70–0,89", client: "Client entscheidet < 0,70" },
};

export function useTheatreCopy() {
  const { lang } = useStoryCopy();
  return { t: lang === "de" ? de : en, lang };
}
