import { useStoryCopy } from "@/mro/components/story/copy";

const en = {
  newRequest: "New request",
  requester: "Requester",
  need: "Need",
  item: "Item",
  startingCost: "Starting cost",
  needBy: "Needed by",
  received: "Received",
  openForm: "Open the form",
  start: (agent: string) => `Start ${agent}`,
  startShort: "Start agent",
  handShort: "Hand off",
  analyseShort: "AI · Run checks",
  checkScope: (signals: number, guards: number) =>
    [signals ? `${signals} confidence signal${signals === 1 ? "" : "s"}` : "", guards ? `${guards} guardrail${guards === 1 ? "" : "s"}` : ""].filter(Boolean).join(" · "),
  notNow: "Not now",
  awaiting: "Request received",
  working: "Working",
  fetched: "fetched",
  fetching: "Fetching sources",
  analyseConfidence: "AI · Score confidence",
  analyseGuardrails: "AI · Run guardrail checks",
  scoringTitle: "Scoring confidence",
  guardTitle: "Running guardrail checks",
  scoringDoc: "confidence score",
  guardDoc: "guardrail verdicts",
  analyseChecks: "AI · Score confidence & run guardrails",
  checksTitle: "Scoring confidence & running guardrails",
  checksDoc: "confidence score & guardrail verdicts",
  confidenceResult: (s: string, band: string) => `Confidence ${s} · ${band}`,
  guardResult: (pass: number, total: number) => `${pass} of ${total} guardrails passed`,
  deciding: "Deciding the routing lane…",
  handover: "Handover",
  closing: "Closing the case",
  done: "Done",
  wakingUp: "Taking over",
  passing: "Passing on",
  sourceFiles: "Source files",
  sourceLead: "The originals each agent read or wrote. Open any of them.",
  noneYet: "Files appear here as the agents fetch them.",
  open: "Open",
  bands: { touchless: "touchless band ≥ 0.90", review: "TCS review band 0.70–0.89", client: "Client decides < 0.70" },
  cancel: "Cancel",
  confirm: "Confirm",
  preparing: "Agent is preparing the decision",
  prepared: "Prepared by the agent",
  pickOne: "Choose an option",
  reasonNeeded: "Type the reason to continue",
  reasonPlaceholder: "Why this option? The reason is saved against the case and shown to audit.",
  savedToCase: "Saved against the case",
  reasonSaved: "Reason recorded",
  from: "From",
  to: "To",
  subject: "Subject",
  body: "Message",
  drafting: "Agent is drafting",
  draftedByAgent: "Drafted by the agent · edit anything before sending",
  editedByYou: "edited before sending",
  sentAsDrafted: "sent as drafted",
  sentTo: "Sent to",
  proposing: "Agent is proposing conditions",
  proposed: "Proposed by the agent",
  agentProposed: "Agent proposed",
  changed: "changed",
  changedCount: (n: number) => `${n} ${n === 1 ? "change" : "changes"} to the proposal`,
  asProposed: "Accepting as proposed",
  required: "Required",
  notRequired: "Not required",
};

type Copy = typeof en;

const de: Copy = {
  newRequest: "Neue Anforderung",
  requester: "Anforderer",
  need: "Bedarf",
  item: "Position",
  startingCost: "Ausgangskosten",
  needBy: "Benötigt bis",
  received: "Eingegangen",
  openForm: "Formular öffnen",
  start: (agent) => `${agent} starten`,
  startShort: "Agent starten",
  handShort: "Übergeben",
  analyseShort: "KI · Prüfen",
  checkScope: (signals, guards) =>
    [signals ? `${signals} Konfidenzsignal${signals === 1 ? "" : "e"}` : "", guards ? `${guards} Leitplanke${guards === 1 ? "" : "n"}` : ""].filter(Boolean).join(" · "),
  notNow: "Später",
  awaiting: "Anforderung eingegangen",
  working: "Arbeitet",
  fetched: "geladen",
  fetching: "Lade Quellen",
  analyseConfidence: "KI · Konfidenz bewerten",
  analyseGuardrails: "KI · Leitplanken prüfen",
  scoringTitle: "Konfidenz wird bewertet",
  guardTitle: "Leitplanken werden geprüft",
  scoringDoc: "Konfidenzwert",
  guardDoc: "Leitplanken-Ergebnis",
  analyseChecks: "KI · Konfidenz bewerten & Leitplanken prüfen",
  checksTitle: "Konfidenz und Leitplanken werden geprüft",
  checksDoc: "Konfidenzwert & Leitplanken-Ergebnis",
  confidenceResult: (s, band) => `Konfidenz ${s} · ${band}`,
  guardResult: (pass, total) => `${pass} von ${total} Leitplanken bestanden`,
  deciding: "Bearbeitungsweg wird entschieden…",
  handover: "Übergabe",
  closing: "Fall wird abgeschlossen",
  done: "Fertig",
  wakingUp: "Übernimmt",
  passing: "Übergibt",
  sourceFiles: "Quelldateien",
  sourceLead: "Die Originale, die jeder Agent gelesen oder erstellt hat.",
  noneYet: "Dateien erscheinen hier, sobald die Agenten sie laden.",
  open: "Öffnen",
  bands: { touchless: "Touchless-Band ≥ 0,90", review: "TCS-Prüfband 0,70–0,89", client: "Client entscheidet < 0,70" },
  cancel: "Abbrechen",
  confirm: "Bestätigen",
  preparing: "Agent bereitet die Entscheidung vor",
  prepared: "Vom Agenten vorbereitet",
  pickOne: "Option wählen",
  reasonNeeded: "Begründung eingeben, um fortzufahren",
  reasonPlaceholder: "Warum diese Option? Die Begründung wird am Fall gespeichert und für das Audit angezeigt.",
  savedToCase: "Wird am Fall gespeichert",
  reasonSaved: "Erfasster Grund",
  from: "Von",
  to: "An",
  subject: "Betreff",
  body: "Nachricht",
  drafting: "Agent schreibt den Entwurf",
  draftedByAgent: "Vom Agenten entworfen · vor dem Senden frei bearbeitbar",
  editedByYou: "vor dem Senden bearbeitet",
  sentAsDrafted: "wie entworfen gesendet",
  sentTo: "Gesendet an",
  proposing: "Agent schlägt Auflagen vor",
  proposed: "Vom Agenten vorgeschlagen",
  agentProposed: "Vorschlag des Agenten",
  changed: "geändert",
  changedCount: (n) => `${n} ${n === 1 ? "Änderung" : "Änderungen"} am Vorschlag`,
  asProposed: "Annahme wie vorgeschlagen",
  required: "Erforderlich",
  notRequired: "Nicht erforderlich",
};

export function useTheatreCopy() {
  const { lang } = useStoryCopy();
  return { t: lang === "de" ? de : en, lang };
}
