import { useT } from "@/mro/lib/i18n";

const en = {
  newRequestTitle: "New request",
  newRequestLead: "Type a catalogue need, or run one of today's five arrivals through its agent chain.",
  todayArrivals: "Today's arrivals",
  inbox: "Arrived today",
  asArrived: "As it arrived",
  agentChain: "Agent chain",
  humanTouchpoints: "Human touchpoints",
  run: "Run the agent chain",
  resume: "Resume the run",
  startingCost: "Starting cost",
  valueBand: "Value band",
  needBy: "Needed by",
  requester: "Requester",
  received: "Received",
  expectTouchless: "Touchless path",
  expectHuman: "Human review",
  back: "New request",
  agentRun: "Agent run",
  ofAgents: (a: number, b: number) => `${a} of ${b} agents done`,
  theRequest: "The request",
  reading: "Reading the handoff",
  checking: "Running guardrails",
  scoring: "Scoring confidence",
  read: "What it read",
  produced: "What it produced",
  confidence: "Confidence",
  guardrails: "Guardrails",
  lane: "Lane decision",
  routeTo: "Routes to",
  postAudit: "Post-audit",
  evidence: "Evidence",
  ran: (s: number) => (s < 120 ? `ran ${s}s` : s < 7200 ? `ran ${Math.round(s / 60)} min` : `${Math.round(s / 3600)} h elapsed`),
  model: "Model",
  weight: "weight",
  handTo: (name: string) => `Hand off to ${name}`,
  closeCase: "Close the case",
  waitingOn: (p: string) => `Waiting on ${p}`,
  decidedBy: (p: string) => `Decided by ${p}`,
  sla: (h: number) => `SLA ${h}h`,
  prefilled: "Prefilled by the agent",
  recordedReason: "Reason recorded",
  escalateIf: "Escalate if",
  then: "Then",
  status: { running: "Agent running", ready: "Ready to hand off", waiting: "Waiting on a person", done: "Case closed", ended: "Ended by decision" },
  outcome: "Outcome",
  outcomeTouchless: "Closed touchless",
  outcomeHuman: (n: number) => `Closed with ${n} human decision${n === 1 ? "" : "s"}`,
  valueRecord: "Value record",
  interventions: "Tail-spend levers",
  flowPath: "Flow path",
  stillOpen: "Still with people after the run",
  locked: "Not started",
  showInput: "Show input",
  hideInput: "Hide input",
  policyHandoff: "Policy hand-off · no person needed",
  rawOutput: "Full agent output",
  pausedNotice: "This agent is paused in Governance. The step waits in the human queue; nothing already dispatched is replayed.",
  reviewAsHint: (now: string, need: string) => `You are reviewing as ${now}. Only the ${need} can decide this.`,
  switchTo: (r: string) => `Review as ${r}`,
};

type Copy = typeof en;

const de: Copy = {
  newRequestTitle: "Neue Anforderung",
  newRequestLead: "Katalogbedarf eingeben oder einen der fünf heutigen Eingänge durch seine Agentenkette führen.",
  todayArrivals: "Heutige Eingänge",
  inbox: "Heute eingegangen",
  asArrived: "Wie eingegangen",
  agentChain: "Agentenkette",
  humanTouchpoints: "Menschliche Kontaktpunkte",
  run: "Agentenkette starten",
  resume: "Lauf fortsetzen",
  startingCost: "Ausgangskosten",
  valueBand: "Wertband",
  needBy: "Benötigt bis",
  requester: "Anforderer",
  received: "Eingegangen",
  expectTouchless: "Ohne Eingriff",
  expectHuman: "Menschliche Prüfung",
  back: "Neue Anforderung",
  agentRun: "Agentenlauf",
  ofAgents: (a, b) => `${a} von ${b} Agenten fertig`,
  theRequest: "Die Anforderung",
  reading: "Übergabe wird gelesen",
  checking: "Leitplanken werden geprüft",
  scoring: "Konfidenz wird bewertet",
  read: "Was er gelesen hat",
  produced: "Was er erzeugt hat",
  confidence: "Konfidenz",
  guardrails: "Leitplanken",
  lane: "Spurentscheidung",
  routeTo: "Weiter an",
  postAudit: "Nachprüfung",
  evidence: "Belege",
  ran: (s) => (s < 120 ? `Laufzeit ${s}s` : s < 7200 ? `Laufzeit ${Math.round(s / 60)} Min.` : `${Math.round(s / 3600)} Std. vergangen`),
  model: "Modell",
  weight: "Gewicht",
  handTo: (name) => `An ${name} übergeben`,
  closeCase: "Fall abschließen",
  waitingOn: (p) => `Wartet auf ${p}`,
  decidedBy: (p) => `Entschieden von ${p}`,
  sla: (h) => `SLA ${h} Std.`,
  prefilled: "Vom Agenten vorausgefüllt",
  recordedReason: "Erfasster Grund",
  escalateIf: "Eskalieren wenn",
  then: "Danach",
  status: { running: "Agent läuft", ready: "Bereit zur Übergabe", waiting: "Wartet auf eine Person", done: "Fall abgeschlossen", ended: "Durch Entscheidung beendet" },
  outcome: "Ergebnis",
  outcomeTouchless: "Ohne Eingriff abgeschlossen",
  outcomeHuman: (n) => `Mit ${n} menschlichen Entscheidung${n === 1 ? "" : "en"} abgeschlossen`,
  valueRecord: "Wertnachweis",
  interventions: "Tail-Spend-Hebel",
  flowPath: "Flusspfad",
  stillOpen: "Nach dem Lauf noch bei Personen",
  locked: "Nicht gestartet",
  showInput: "Eingabe zeigen",
  hideInput: "Eingabe ausblenden",
  policyHandoff: "Übergabe per Richtlinie · keine Person nötig",
  rawOutput: "Vollständige Agentenausgabe",
  pausedNotice: "Dieser Agent ist in Governance pausiert. Der Schritt wartet in der menschlichen Warteschlange; bereits Übermitteltes wird nicht wiederholt.",
  reviewAsHint: (now, need) => `Sie prüfen als ${now}. Nur ${need} kann das entscheiden.`,
  switchTo: (r) => `Als ${r} prüfen`,
};

export function useStoryCopy() {
  const { lang } = useT();
  return { c: lang === "de" ? de : en, lang: lang === "de" ? ("de" as const) : ("en" as const) };
}
